// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHpaSu12toqVfVNdrhEmM7SvcIoqLRhYk',
    appId: '1:333311307508:web:2e3ccde06e7614270fb8a1',
    messagingSenderId: '333311307508',
    projectId: 'agrisense-65a36',
    authDomain: 'agrisense-65a36.firebaseapp.com',
    storageBucket: 'agrisense-65a36.firebasestorage.app',
    measurementId: 'G-MMBBDHPL34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtse4kjQEzvvDbD2XoPwaMT1KivUt7nMk',
    appId: '1:333311307508:android:991dbe61478b9c720fb8a1',
    messagingSenderId: '333311307508',
    projectId: 'agrisense-65a36',
    storageBucket: 'agrisense-65a36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxSHxjqGJaCC9tuEWXhI_b5LqwGjN52Q0',
    appId: '1:333311307508:ios:3ee3d8edfc45cf650fb8a1',
    messagingSenderId: '333311307508',
    projectId: 'agrisense-65a36',
    storageBucket: 'agrisense-65a36.firebasestorage.app',
    iosBundleId: 'com.example.agrisense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxSHxjqGJaCC9tuEWXhI_b5LqwGjN52Q0',
    appId: '1:333311307508:ios:3ee3d8edfc45cf650fb8a1',
    messagingSenderId: '333311307508',
    projectId: 'agrisense-65a36',
    storageBucket: 'agrisense-65a36.firebasestorage.app',
    iosBundleId: 'com.example.agrisense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHpaSu12toqVfVNdrhEmM7SvcIoqLRhYk',
    appId: '1:333311307508:web:0b4eb77c05dcf1ed0fb8a1',
    messagingSenderId: '333311307508',
    projectId: 'agrisense-65a36',
    authDomain: 'agrisense-65a36.firebaseapp.com',
    storageBucket: 'agrisense-65a36.firebasestorage.app',
    measurementId: 'G-5E9EP7VJN8',
  );
}
